language: go
sudo: false
go:
    - 1.5
before_install: ./scripts/hack/symlink-gopath-travisci
install: make get-deps
script:
    # Full tests require building/running docker containers; short only for now
    - make short-test
